[rospy.client][INFO] 2017-06-10 15:31:04,099: init_node, name[/marker_control_4883_1497133864054], pid[4883]
[xmlrpc][INFO] 2017-06-10 15:31:04,099: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 15:31:04,104: Started XML-RPC server [http://ip-172-31-26-229:51808/]
[rospy.init][INFO] 2017-06-10 15:31:04,104: ROS Slave URI: [http://ip-172-31-26-229:51808/]
[rospy.impl.masterslave][INFO] 2017-06-10 15:31:04,108: _ready: http://ip-172-31-26-229:51808/
[rospy.registration][INFO] 2017-06-10 15:31:04,116: Registering with master node http://localhost:44448
[xmlrpc][INFO] 2017-06-10 15:31:04,116: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-06-10 15:31:04,211: registered with master
[rospy.rosout][INFO] 2017-06-10 15:31:04,215: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 15:31:04,224: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 15:31:04,229: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 15:31:04,435: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 15:31:04,542: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 15:31:04,557: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 15:31:04,561: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 15:31:04,944: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 15:34:55,486: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-10 15:34:55,558: topic[/control_markers/feedback] adding connection to [http://ip-172-31-26-229:47432/], count 0
[rospy.internal][INFO] 2017-06-10 15:35:04,168: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:39250/], count 0
[rospy.internal][INFO] 2017-06-10 15:35:04,177: topic[/motion_planning_goal] adding connection to [/move_arm_8353_1497134103736], count 0
[rospy.internal][INFO] 2017-06-10 15:35:19,293: topic[/joint_states] adding connection to [http://ip-172-31-26-229:53350/], count 0
[rospy.internal][INFO] 2017-06-10 15:35:19,294: topic[/tf] adding connection to [http://ip-172-31-26-229:55659/], count 0
[rospy.internal][INFO] 2017-06-10 15:35:19,415: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][ERROR] 2017-06-10 15:35:24,042: Unable to initiate TCP/IP socket to ip-172-31-26-229:35014 (http://ip-172-31-26-229:39250/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2017-06-10 15:35:24,053: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-10 15:35:24,058: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2017-06-10 15:35:25,184: Unknown error initiating TCP/IP socket to ip-172-31-26-229:35014 (http://ip-172-31-26-229:39250/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-10 15:35:25,190: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:39250/
[rospy.internal][INFO] 2017-06-10 15:35:30,224: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][INFO] 2017-06-10 15:36:00,777: topic[/motion_planning_goal] removing connection to /move_arm_8353_1497134103736
[rospy.internal][WARNING] 2017-06-10 15:36:35,347: Unknown error initiating TCP/IP socket to ip-172-31-26-229:32904 (http://ip-172-31-26-229:53350/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

