[rospy.client][INFO] 2017-06-10 20:04:09,453: init_node, name[/marker_control_26317_1497150249363], pid[26317]
[xmlrpc][INFO] 2017-06-10 20:04:09,453: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 20:04:09,458: Started XML-RPC server [http://ip-172-31-19-100:53836/]
[rospy.init][INFO] 2017-06-10 20:04:09,458: ROS Slave URI: [http://ip-172-31-19-100:53836/]
[rospy.impl.masterslave][INFO] 2017-06-10 20:04:09,463: _ready: http://ip-172-31-19-100:53836/
[rospy.registration][INFO] 2017-06-10 20:04:09,472: Registering with master node http://localhost:52295
[xmlrpc][INFO] 2017-06-10 20:04:09,472: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-06-10 20:04:09,568: registered with master
[rospy.rosout][INFO] 2017-06-10 20:04:09,576: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 20:04:09,588: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 20:04:09,593: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 20:04:09,882: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 20:04:09,886: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 20:04:09,895: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 20:04:09,902: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 20:04:10,403: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 20:04:46,987: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-10 20:04:47,098: topic[/control_markers/feedback] adding connection to [http://ip-172-31-19-100:37408/], count 0
[rospy.internal][INFO] 2017-06-10 20:05:21,758: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:36005/], count 0
[rospy.internal][INFO] 2017-06-10 20:05:21,762: topic[/motion_planning_goal] adding connection to [/move_arm_28450_1497150320965], count 0
[rospy.internal][INFO] 2017-06-10 20:05:27,883: topic[/tf] adding connection to [http://ip-172-31-19-100:48904/], count 0
[rospy.internal][INFO] 2017-06-10 20:05:27,900: topic[/joint_states] adding connection to [http://ip-172-31-19-100:52574/], count 0
[rospy.internal][INFO] 2017-06-10 20:05:28,172: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-10 20:05:35,512: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][ERROR] 2017-06-10 20:06:17,514: Unable to initiate TCP/IP socket to ip-172-31-19-100:57443 (http://ip-172-31-19-100:36005/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2017-06-10 20:06:17,530: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-10 20:06:17,535: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2017-06-10 20:06:18,777: Unknown error initiating TCP/IP socket to ip-172-31-19-100:57443 (http://ip-172-31-19-100:36005/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-10 20:06:18,782: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:36005/
[rospy.internal][INFO] 2017-06-10 20:07:15,311: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:60205/], count 0
[rospy.internal][INFO] 2017-06-10 20:07:15,318: topic[/motion_planning_goal] adding connection to [/move_arm_7125_1497150434788], count 1
[rospy.internal][INFO] 2017-06-10 20:07:30,647: topic[/motion_planning_goal] removing connection to /move_arm_28450_1497150320965
[rospy.internal][ERROR] 2017-06-10 20:08:49,005: Unable to initiate TCP/IP socket to ip-172-31-19-100:60381 (http://ip-172-31-19-100:60205/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-10 20:08:50,245: Unknown error initiating TCP/IP socket to ip-172-31-19-100:60381 (http://ip-172-31-19-100:60205/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-10 20:08:50,250: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:60205/
