[rospy.client][INFO] 2017-06-10 00:50:52,400: init_node, name[/marker_control_12653_1497081052358], pid[12653]
[xmlrpc][INFO] 2017-06-10 00:50:52,400: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 00:50:52,404: Started XML-RPC server [http://ip-172-31-19-100:51697/]
[rospy.init][INFO] 2017-06-10 00:50:52,404: ROS Slave URI: [http://ip-172-31-19-100:51697/]
[rospy.impl.masterslave][INFO] 2017-06-10 00:50:52,408: _ready: http://ip-172-31-19-100:51697/
[xmlrpc][INFO] 2017-06-10 00:50:52,415: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-10 00:50:52,415: Registering with master node http://localhost:35711
[rospy.init][INFO] 2017-06-10 00:50:52,511: registered with master
[rospy.rosout][INFO] 2017-06-10 00:50:52,515: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 00:50:52,524: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 00:50:52,529: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 00:50:52,731: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 00:50:52,838: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 00:50:52,853: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 00:50:52,857: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 00:50:53,240: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 00:50:57,776: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-10 00:50:57,870: topic[/control_markers/feedback] adding connection to [http://ip-172-31-19-100:55247/], count 0
[rospy.internal][INFO] 2017-06-10 00:51:08,840: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:54007/], count 0
[rospy.internal][INFO] 2017-06-10 00:51:08,848: topic[/motion_planning_goal] adding connection to [/move_arm_13576_1497081068468], count 0
[rospy.internal][INFO] 2017-06-10 00:53:44,730: topic[/tf] adding connection to [http://ip-172-31-19-100:41513/], count 0
[rospy.internal][INFO] 2017-06-10 00:53:44,730: topic[/joint_states] adding connection to [http://ip-172-31-19-100:33200/], count 0
[rospy.internal][INFO] 2017-06-10 00:53:44,966: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-10 00:53:57,905: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][ERROR] 2017-06-10 00:54:18,725: Unable to initiate TCP/IP socket to ip-172-31-19-100:54740 (http://ip-172-31-19-100:55247/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: Internal error processing topic [/control_markers/feedback]

[rospy.internal][WARNING] 2017-06-10 00:54:18,742: Unknown error initiating TCP/IP socket to ip-172-31-19-100:32944 (http://ip-172-31-19-100:54007/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-10 00:54:18,746: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:54007/
[rospy.internal][ERROR] 2017-06-10 00:54:19,728: Unable to initiate TCP/IP socket to ip-172-31-19-100:54740 (http://ip-172-31-19-100:55247/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

