[rospy.client][INFO] 2017-06-10 00:33:15,652: init_node, name[/marker_control_21620_1497079995606], pid[21620]
[xmlrpc][INFO] 2017-06-10 00:33:15,652: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 00:33:15,656: Started XML-RPC server [http://ip-172-31-26-229:35101/]
[rospy.init][INFO] 2017-06-10 00:33:15,656: ROS Slave URI: [http://ip-172-31-26-229:35101/]
[rospy.impl.masterslave][INFO] 2017-06-10 00:33:15,660: _ready: http://ip-172-31-26-229:35101/
[xmlrpc][INFO] 2017-06-10 00:33:15,668: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-10 00:33:15,668: Registering with master node http://localhost:42265
[rospy.init][INFO] 2017-06-10 00:33:15,764: registered with master
[rospy.rosout][INFO] 2017-06-10 00:33:15,768: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 00:33:15,777: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 00:33:15,782: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 00:33:16,059: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 00:33:16,071: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 00:33:16,082: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 00:33:16,086: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 00:33:16,573: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 00:33:20,837: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-10 00:33:20,893: topic[/control_markers/feedback] adding connection to [http://ip-172-31-26-229:33146/], count 0
[rospy.internal][INFO] 2017-06-10 00:33:27,776: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:42213/], count 0
[rospy.internal][INFO] 2017-06-10 00:33:27,781: topic[/motion_planning_goal] adding connection to [/move_arm_22328_1497080007380], count 0
[rospy.internal][INFO] 2017-06-10 00:33:37,177: topic[/tf] adding connection to [http://ip-172-31-26-229:35505/], count 0
[rospy.internal][INFO] 2017-06-10 00:33:37,182: topic[/joint_states] adding connection to [http://ip-172-31-26-229:35855/], count 0
[rospy.internal][INFO] 2017-06-10 00:33:37,342: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][ERROR] 2017-06-10 00:33:47,836: Unable to initiate TCP/IP socket to ip-172-31-26-229:57943 (http://ip-172-31-26-229:42213/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-10 00:33:49,005: Unknown error initiating TCP/IP socket to ip-172-31-26-229:57943 (http://ip-172-31-26-229:42213/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-10 00:33:49,009: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:42213/
[rospy.internal][INFO] 2017-06-10 00:33:50,711: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][INFO] 2017-06-10 00:34:21,244: topic[/motion_planning_goal] removing connection to /move_arm_22328_1497080007380
[rospy.internal][INFO] 2017-06-10 00:34:47,079: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:55079/], count 0
[rospy.internal][INFO] 2017-06-10 00:34:47,083: topic[/motion_planning_goal] adding connection to [/move_arm_24566_1497080086692], count 0
[rospy.internal][WARNING] 2017-06-10 00:34:59,345: Unknown error initiating TCP/IP socket to ip-172-31-26-229:37187 (http://ip-172-31-26-229:55079/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-10 00:34:59,346: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:55079/
