[rospy.client][INFO] 2017-06-10 18:58:27,169: init_node, name[/marker_control_22794_1497146307109], pid[22794]
[xmlrpc][INFO] 2017-06-10 18:58:27,169: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 18:58:27,173: Started XML-RPC server [http://ip-172-31-26-229:54997/]
[rospy.impl.masterslave][INFO] 2017-06-10 18:58:27,178: _ready: http://ip-172-31-26-229:54997/
[rospy.init][INFO] 2017-06-10 18:58:27,174: ROS Slave URI: [http://ip-172-31-26-229:54997/]
[xmlrpc][INFO] 2017-06-10 18:58:27,183: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-10 18:58:27,183: Registering with master node http://localhost:53261
[rospy.init][INFO] 2017-06-10 18:58:27,286: registered with master
[rospy.rosout][INFO] 2017-06-10 18:58:27,290: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 18:58:27,300: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 18:58:27,305: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 18:58:27,530: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 18:58:27,539: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 18:58:27,641: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 18:58:27,645: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 18:58:28,044: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 18:59:23,021: topic[/joint_trajectory] adding connection to [http://ip-172-31-26-229:48615/], count 0
[rospy.internal][INFO] 2017-06-10 18:59:23,887: topic[/motion_planning_goal] adding connection to [/move_arm_23434_1497146362594], count 0
[rospy.internal][INFO] 2017-06-10 18:59:25,493: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-10 18:59:25,621: topic[/control_markers/feedback] adding connection to [http://ip-172-31-26-229:34326/], count 0
[rospy.internal][INFO] 2017-06-10 19:02:49,320: topic[/tf] adding connection to [http://ip-172-31-26-229:60496/], count 0
[rospy.internal][INFO] 2017-06-10 19:02:49,334: topic[/joint_states] adding connection to [http://ip-172-31-26-229:52433/], count 0
[rospy.internal][INFO] 2017-06-10 19:02:49,588: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][ERROR] 2017-06-10 19:02:56,436: Unable to initiate TCP/IP socket to ip-172-31-26-229:45199 (http://ip-172-31-26-229:48615/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-06-10 19:02:56,878: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][WARNING] 2017-06-10 19:02:57,441: Unknown error initiating TCP/IP socket to ip-172-31-26-229:45199 (http://ip-172-31-26-229:48615/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-10 19:02:57,445: topic[/joint_trajectory] removing connection to http://ip-172-31-26-229:48615/
[rospy.internal][INFO] 2017-06-10 19:03:27,386: topic[/motion_planning_goal] removing connection to /move_arm_23434_1497146362594
[rospy.internal][WARNING] 2017-06-10 19:03:51,686: Unknown error initiating TCP/IP socket to ip-172-31-26-229:34518 (http://ip-172-31-26-229:52433/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

