[rospy.client][INFO] 2017-06-10 14:39:19,920: init_node, name[/move_arm_4749_1497130759875], pid[4749]
[xmlrpc][INFO] 2017-06-10 14:39:19,920: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 14:39:19,925: Started XML-RPC server [http://ip-172-31-19-100:56077/]
[rospy.init][INFO] 2017-06-10 14:39:19,925: ROS Slave URI: [http://ip-172-31-19-100:56077/]
[rospy.impl.masterslave][INFO] 2017-06-10 14:39:19,929: _ready: http://ip-172-31-19-100:56077/
[xmlrpc][INFO] 2017-06-10 14:39:19,938: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-10 14:39:19,938: Registering with master node http://localhost:54190
[rospy.init][INFO] 2017-06-10 14:39:20,033: registered with master
[rospy.rosout][INFO] 2017-06-10 14:39:20,037: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 14:39:20,046: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 14:39:20,051: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 14:39:20,306: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:54987/], count 0
[rospy.internal][INFO] 2017-06-10 14:39:20,308: topic[/joint_states] adding connection to [http://ip-172-31-19-100:45378/], count 0
[rospy.internal][INFO] 2017-06-10 14:39:20,311: topic[/joint_trajectory] adding connection to [/marker_control_21804_1497130421421], count 0
[rospy.internal][INFO] 2017-06-10 14:39:21,245: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 14:39:21,248: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-10 14:39:21,280: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 14:39:21,284: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-10 15:07:36,966: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-10 15:07:36,999: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 15:07:37,003: topic[/joint_trajectory] removing connection to /marker_control_21804_1497130421421
[rospy.internal][INFO] 2017-06-10 15:07:37,007: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-10 15:07:37,011: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-10 15:07:37,015: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 15:07:37,019: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:54987/
[rospy.internal][INFO] 2017-06-10 15:07:37,023: topic[/joint_states] removing connection to http://ip-172-31-19-100:45378/
[rospy.impl.masterslave][INFO] 2017-06-10 15:07:37,027: signal-2
[rospy.topics][WARNING] 2017-06-10 15:07:37,038: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f6dac2ef410>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 395, in move_arm_cb
    trajectory = self.project_plan(numpy.array(q_start), q_goal, self.q_min, self.q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 380, in project_plan
    q_list = self.motion_plan(q_start, q_goal, q_min, q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 328, in motion_plan
    if self.is_collision_free(closest_node.value, point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 292, in is_collision_free
    if not self.is_state_valid(check_point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-10 15:07:37,595: signal_shutdown [atexit]
