[rospy.client][INFO] 2017-06-09 18:19:29,982: init_node, name[/move_arm_7099_1497057569941], pid[7099]
[xmlrpc][INFO] 2017-06-09 18:19:29,982: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 18:19:29,986: Started XML-RPC server [http://ip-172-31-26-229:39201/]
[rospy.init][INFO] 2017-06-09 18:19:29,987: ROS Slave URI: [http://ip-172-31-26-229:39201/]
[rospy.impl.masterslave][INFO] 2017-06-09 18:19:29,990: _ready: http://ip-172-31-26-229:39201/
[xmlrpc][INFO] 2017-06-09 18:19:30,002: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 18:19:30,002: Registering with master node http://localhost:32860
[rospy.init][INFO] 2017-06-09 18:19:30,097: registered with master
[rospy.rosout][INFO] 2017-06-09 18:19:30,102: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 18:19:30,110: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 18:19:30,115: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 18:19:30,343: topic[/joint_states] adding connection to [http://ip-172-31-26-229:43708/], count 0
[rospy.internal][INFO] 2017-06-09 18:19:30,344: topic[/motion_planning_goal] adding connection to [http://ip-172-31-26-229:59695/], count 0
[rospy.internal][INFO] 2017-06-09 18:19:30,345: topic[/joint_trajectory] adding connection to [/marker_control_5973_1497057538941], count 0
[rospy.internal][INFO] 2017-06-09 18:19:31,173: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 18:19:31,177: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-09 18:19:31,207: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:19:31,212: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-09 18:23:26,518: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-09 18:23:26,551: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:23:26,556: topic[/joint_trajectory] removing connection to /marker_control_5973_1497057538941
[rospy.internal][INFO] 2017-06-09 18:23:26,560: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-09 18:23:26,564: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-09 18:23:26,568: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:23:26,571: topic[/motion_planning_goal] removing connection to http://ip-172-31-26-229:59695/
[rospy.internal][INFO] 2017-06-09 18:23:26,575: topic[/joint_states] removing connection to http://ip-172-31-26-229:43708/
[rospy.impl.masterslave][INFO] 2017-06-09 18:23:26,579: signal-2
[rospy.topics][WARNING] 2017-06-09 18:23:26,588: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f3856072410>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 331, in move_arm_cb
    trajectory = self.project_plan(numpy.array(q_start), q_goal, self.q_min, self.q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 316, in project_plan
    q_list = self.motion_plan(q_start, q_goal, q_min, q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 274, in motion_plan
    if self.is_collision_free(new_node.value, point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 248, in is_collision_free
    if not self.is_state_valid(check_point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-09 18:23:27,147: signal_shutdown [atexit]
