[rospy.client][INFO] 2017-06-09 18:37:50,587: init_node, name[/move_arm_22807_1497058670548], pid[22807]
[xmlrpc][INFO] 2017-06-09 18:37:50,587: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 18:37:50,591: Started XML-RPC server [http://ip-172-31-26-229:43399/]
[rospy.init][INFO] 2017-06-09 18:37:50,591: ROS Slave URI: [http://ip-172-31-26-229:43399/]
[rospy.impl.masterslave][INFO] 2017-06-09 18:37:50,595: _ready: http://ip-172-31-26-229:43399/
[xmlrpc][INFO] 2017-06-09 18:37:50,604: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 18:37:50,604: Registering with master node http://localhost:42174
[rospy.init][INFO] 2017-06-09 18:37:50,699: registered with master
[rospy.rosout][INFO] 2017-06-09 18:37:50,703: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 18:37:50,712: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 18:37:50,716: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 18:37:50,941: topic[/joint_states] adding connection to [http://ip-172-31-26-229:44646/], count 0
[rospy.internal][INFO] 2017-06-09 18:37:50,940: topic[/motion_planning_goal] adding connection to [http://ip-172-31-26-229:58570/], count 0
[rospy.internal][INFO] 2017-06-09 18:37:50,946: topic[/joint_trajectory] adding connection to [/marker_control_21688_1497058647312], count 0
[rospy.internal][INFO] 2017-06-09 18:37:51,794: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 18:37:51,798: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-09 18:37:51,882: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:37:51,886: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-09 18:41:31,572: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-09 18:41:31,604: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:41:31,608: topic[/joint_trajectory] removing connection to /marker_control_21688_1497058647312
[rospy.internal][INFO] 2017-06-09 18:41:31,612: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-09 18:41:31,616: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-09 18:41:31,620: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:41:31,624: topic[/motion_planning_goal] removing connection to http://ip-172-31-26-229:58570/
[rospy.internal][INFO] 2017-06-09 18:41:31,629: topic[/joint_states] removing connection to http://ip-172-31-26-229:44646/
[rospy.impl.masterslave][INFO] 2017-06-09 18:41:31,632: signal-2
[rospy.topics][WARNING] 2017-06-09 18:41:31,644: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f4c09ee9450>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 337, in move_arm_cb
    return
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 322, in project_plan
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 278, in motion_plan
    new_node = TreeNode(point)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 248, in is_collision_free
    print('is_collision_free: check_point = {}'.format(check_point.value))
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-09 18:41:32,251: signal_shutdown [atexit]
