[rospy.client][INFO] 2017-06-05 17:35:48,009: init_node, name[/cartesian_control_21762_1496709347972], pid[21762]
[xmlrpc][INFO] 2017-06-05 17:35:48,009: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-05 17:35:48,013: Started XML-RPC server [http://ip-172-31-19-100:36908/]
[rospy.init][INFO] 2017-06-05 17:35:48,013: ROS Slave URI: [http://ip-172-31-19-100:36908/]
[rospy.impl.masterslave][INFO] 2017-06-05 17:35:48,019: _ready: http://ip-172-31-19-100:36908/
[xmlrpc][INFO] 2017-06-05 17:35:48,035: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-05 17:35:48,035: Registering with master node http://localhost:52855
[rospy.init][INFO] 2017-06-05 17:35:48,131: registered with master
[rospy.rosout][INFO] 2017-06-05 17:35:48,137: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-05 17:35:48,149: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-05 17:35:48,153: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-05 17:35:48,216: topic[/joint_states] adding connection to [http://ip-172-31-19-100:37610/], count 0
[rospy.internal][INFO] 2017-06-05 17:35:48,414: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-05 17:35:48,421: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-05 17:35:48,427: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-05 17:35:48,623: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-05 17:35:48,677: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][INFO] 2017-06-05 17:35:57,878: topic[/control_markers/feedback] adding connection to [http://ip-172-31-19-100:33454/], count 0
[rospy.internal][INFO] 2017-06-05 17:36:22,761: topic[/redundancy_command] adding connection to [/cartesian_control_22479_1496709382508], count 0
[rospy.internal][INFO] 2017-06-05 17:36:22,765: topic[/cartesian_command] adding connection to [/cartesian_control_22479_1496709382508], count 0
[rosout][WARNING] 2017-06-05 17:36:47,558: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-05 17:36:47,562: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-06-05 17:41:03,611: topic[/redundancy_command] adding connection to [/cartesian_control_23968_1496709663364], count 1
[rospy.internal][INFO] 2017-06-05 17:41:03,616: topic[/cartesian_command] adding connection to [/cartesian_control_23968_1496709663364], count 1
[rospy.internal][INFO] 2017-06-05 17:41:03,619: topic[/cartesian_command] removing connection to /cartesian_control_22479_1496709382508
[rospy.internal][INFO] 2017-06-05 17:42:02,513: topic[/redundancy_command] adding connection to [/cartesian_control_24741_1496709722264], count 2
[rospy.internal][INFO] 2017-06-05 17:42:02,517: topic[/cartesian_command] adding connection to [/cartesian_control_24741_1496709722264], count 1
[rospy.internal][INFO] 2017-06-05 17:42:09,503: topic[/cartesian_command] removing connection to /cartesian_control_23968_1496709663364
[rosout][WARNING] 2017-06-05 17:43:02,073: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-05 17:43:02,077: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-06-05 17:43:06,651: topic[/redundancy_command] adding connection to [/cartesian_control_25384_1496709786403], count 3
[rospy.internal][INFO] 2017-06-05 17:43:06,657: topic[/cartesian_command] adding connection to [/cartesian_control_25384_1496709786403], count 1
[rospy.internal][INFO] 2017-06-05 17:43:15,803: topic[/cartesian_command] removing connection to /cartesian_control_24741_1496709722264
[rospy.internal][INFO] 2017-06-05 18:41:31,797: topic[/cartesian_command] adding connection to [/cartesian_control_8170_1496713291544], count 1
[rospy.internal][INFO] 2017-06-05 18:41:31,799: topic[/cartesian_command] removing connection to /cartesian_control_25384_1496709786403
[rospy.internal][INFO] 2017-06-05 18:41:31,803: topic[/redundancy_command] adding connection to [/cartesian_control_8170_1496713291544], count 4
[rosout][WARNING] 2017-06-05 18:44:17,460: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-05 18:44:17,461: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-06-05 18:44:20,343: topic[/redundancy_command] adding connection to [/cartesian_control_9768_1496713460106], count 5
[rospy.internal][INFO] 2017-06-05 18:44:20,347: topic[/cartesian_command] adding connection to [/cartesian_control_9768_1496713460106], count 1
[rospy.internal][INFO] 2017-06-05 18:44:20,351: topic[/cartesian_command] removing connection to /cartesian_control_8170_1496713291544
[rosout][WARNING] 2017-06-05 18:47:32,177: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-05 18:47:32,178: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-06-05 18:47:35,911: topic[/redundancy_command] adding connection to [/cartesian_control_11437_1496713655667], count 6
[rospy.internal][INFO] 2017-06-05 18:47:35,916: topic[/cartesian_command] adding connection to [/cartesian_control_11437_1496713655667], count 1
[rospy.internal][INFO] 2017-06-05 18:47:35,920: topic[/cartesian_command] removing connection to /cartesian_control_9768_1496713460106
[rospy.internal][INFO] 2017-06-05 18:49:14,828: topic[/cartesian_command] adding connection to [/cartesian_control_12203_1496713754553], count 1
[rospy.internal][INFO] 2017-06-05 18:49:14,829: topic[/cartesian_command] removing connection to /cartesian_control_11437_1496713655667
[rospy.internal][INFO] 2017-06-05 18:49:14,832: topic[/redundancy_command] adding connection to [/cartesian_control_12203_1496713754553], count 7
[rospy.internal][INFO] 2017-06-05 18:51:39,397: topic[/redundancy_command] adding connection to [/cartesian_control_13603_1496713899141], count 8
[rospy.internal][INFO] 2017-06-05 18:51:39,400: topic[/cartesian_command] adding connection to [/cartesian_control_13603_1496713899141], count 1
[rospy.internal][INFO] 2017-06-05 18:51:39,404: topic[/cartesian_command] removing connection to /cartesian_control_12203_1496713754553
[rospy.internal][INFO] 2017-06-05 18:53:55,308: topic[/redundancy_command] adding connection to [/cartesian_control_14089_1496714035065], count 9
[rospy.internal][INFO] 2017-06-05 18:53:55,311: topic[/cartesian_command] adding connection to [/cartesian_control_14089_1496714035065], count 1
[rospy.internal][INFO] 2017-06-05 18:53:55,315: topic[/cartesian_command] removing connection to /cartesian_control_13603_1496713899141
[rosout][WARNING] 2017-06-05 18:55:05,165: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-05 18:55:05,165: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-06-05 18:55:08,011: topic[/redundancy_command] adding connection to [/cartesian_control_14445_1496714107773], count 10
[rospy.internal][INFO] 2017-06-05 18:55:08,017: topic[/cartesian_command] adding connection to [/cartesian_control_14445_1496714107773], count 1
[rospy.internal][INFO] 2017-06-05 18:55:08,021: topic[/cartesian_command] removing connection to /cartesian_control_14089_1496714035065
[rosout][WARNING] 2017-06-05 18:56:31,626: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-05 18:56:31,626: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-06-05 18:56:34,453: topic[/redundancy_command] adding connection to [/cartesian_control_15058_1496714194211], count 11
[rospy.internal][INFO] 2017-06-05 18:56:34,457: topic[/cartesian_command] adding connection to [/cartesian_control_15058_1496714194211], count 1
[rospy.internal][INFO] 2017-06-05 18:56:34,461: topic[/cartesian_command] removing connection to /cartesian_control_14445_1496714107773
[rospy.internal][INFO] 2017-06-05 18:57:29,063: topic[/cartesian_command] adding connection to [/cartesian_control_15512_1496714248826], count 1
[rospy.internal][INFO] 2017-06-05 18:57:29,063: topic[/cartesian_command] removing connection to /cartesian_control_15058_1496714194211
[rospy.internal][INFO] 2017-06-05 18:57:29,067: topic[/redundancy_command] adding connection to [/cartesian_control_15512_1496714248826], count 12
[rosout][WARNING] 2017-06-05 18:58:05,146: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-05 18:58:05,147: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-06-05 18:58:25,730: topic[/redundancy_command] adding connection to [/cartesian_control_16089_1496714305483], count 13
[rospy.internal][INFO] 2017-06-05 18:58:25,736: topic[/cartesian_command] adding connection to [/cartesian_control_16089_1496714305483], count 1
[rospy.internal][INFO] 2017-06-05 18:58:32,903: topic[/cartesian_command] removing connection to /cartesian_control_15512_1496714248826
[rospy.internal][ERROR] 2017-06-05 18:59:15,152: Unable to initiate TCP/IP socket to ip-172-31-19-100:57231 (http://ip-172-31-19-100:33454/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: Internal error processing topic [/control_markers/feedback]

[rospy.internal][ERROR] 2017-06-05 18:59:16,156: Unable to initiate TCP/IP socket to ip-172-31-19-100:57231 (http://ip-172-31-19-100:33454/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

