[rospy.client][INFO] 2017-06-05 19:04:17,800: init_node, name[/cartesian_control_19914_1496714657763], pid[19914]
[xmlrpc][INFO] 2017-06-05 19:04:17,800: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-05 19:04:17,805: Started XML-RPC server [http://ip-172-31-19-100:37628/]
[rospy.init][INFO] 2017-06-05 19:04:17,805: ROS Slave URI: [http://ip-172-31-19-100:37628/]
[rospy.impl.masterslave][INFO] 2017-06-05 19:04:17,808: _ready: http://ip-172-31-19-100:37628/
[xmlrpc][INFO] 2017-06-05 19:04:17,816: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-05 19:04:17,816: Registering with master node http://localhost:54643
[rospy.init][INFO] 2017-06-05 19:04:17,912: registered with master
[rospy.rosout][INFO] 2017-06-05 19:04:17,916: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-05 19:04:17,927: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-05 19:04:17,932: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-05 19:04:18,041: topic[/joint_states] adding connection to [http://ip-172-31-19-100:50138/], count 0
[rospy.internal][INFO] 2017-06-05 19:04:18,133: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-05 19:04:18,143: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-05 19:04:18,226: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-05 19:04:18,428: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-05 19:04:18,470: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][INFO] 2017-06-05 19:06:25,900: topic[/control_markers/feedback] adding connection to [http://ip-172-31-19-100:59570/], count 0
[rospy.internal][INFO] 2017-06-05 19:14:27,866: topic[/redundancy_command] adding connection to [/cartesian_control_27257_1496715267620], count 0
[rospy.internal][INFO] 2017-06-05 19:14:27,870: topic[/cartesian_command] adding connection to [/cartesian_control_27257_1496715267620], count 0
[rosout][WARNING] 2017-06-05 19:14:53,978: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-05 19:14:53,980: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-06-05 19:14:54,293: topic[/cartesian_command] removing connection to /cartesian_control_27257_1496715267620
[rospy.internal][INFO] 2017-06-05 19:16:11,893: topic[/cartesian_command] adding connection to [/cartesian_control_28285_1496715371647], count 0
[rospy.internal][INFO] 2017-06-05 19:16:11,896: topic[/redundancy_command] adding connection to [/cartesian_control_28285_1496715371647], count 1
[rospy.internal][ERROR] 2017-06-05 19:16:24,736: Unable to initiate TCP/IP socket to ip-172-31-19-100:53178 (http://ip-172-31-19-100:59570/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: Internal error processing topic [/control_markers/feedback]

[rospy.internal][ERROR] 2017-06-05 19:16:25,737: Unable to initiate TCP/IP socket to ip-172-31-19-100:53178 (http://ip-172-31-19-100:59570/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: [/rosbridge_websocket] is not a publisher of [/control_markers/feedback]. Topics are [['/rosout', 'rosgraph_msgs/Log']]

